[package]
name = "rasp-pi-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_ws281x = "0.5.1"
sled = {git = "https://github.com/DavJCosby/sled/"}