center_point = [0.285, -1.25]
density = 60.0

[[line_segment]]
start = [-0.40, 0]
end = [0.0, 0.0]

[[line_segment]]
start = [0.0, 0.0]
end = [-0.66, 0.0]

[[line_segment]]
start = [-0.66, 0]
end = [-0.66, -2.49]

[[line_segment]]
start = [-0.66, -2.49]
end = [0.18, -2.49]

[[line_segment]]
start = [0.18, -2.49]
end = [0.18, -3.19]

[[line_segment]]
start = [0.18, -3.19]
end = [1.10, -3.19]

# [[line_segment]]
# start = [1.32, -3.19]
# end = [2.48, -3.19]

# [[line_segment]]
# start = [2.48, -3.2]
# end = [2.48, -0.14]

#[[line_segment]]
#start = [2.48, -0.14]
#end = [2.34, 0]

#[[line_segment]]
#start = [2.34, 0]
# end = [1.8, 0]